
#local credential store information
keyring_entry_name = "QUAGGIN_REFRESH_TOKEN"
keyring_username = "QUAGGIN_SECURITY"

[authorization_token_configuration]
oauth2_link = "https://gw2.me/oauth2/authorize"
redirect_routing_endpoint = "/callback"
redirect_uri="http://127.0.0.1/callback"
client_id="b185490f-b41b-40bc-9b1d-a5d7eb22ac68"
response_type="code"
scope="identify"
prompt="consent"
include_granted_scopes=true

[access_token_configuration]
endpoint_url = "https://gw2.me/api/token"
grant_type = "authorization_code"
client_id="b185490f-b41b-40bc-9b1d-a5d7eb22ac68"
redirect_uri = "http://127.0.0.1"
